services:

  tgbot:
    image: ghcr.io/skoval67/easybot:${image_tag}
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      RAPID_API_KEY: ${RAPID_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - bothistory:/app/history
    ports:
      - 5678:5678

volumes:
  bothistory:
